apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mydocs-ingress
  namespace: mydocs
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - mydocs.example.com
      secretName: mydocs-tls
